---
title: "Kachelkarte der 299 Wahlkreise von Deutschland" 
description: ""
author:
    - name: "Cédric Scherer"
      url: https://cedricscherer.com
    - name: "Ansgar Wolsing"
      url: 
date: "`r Sys.Date()`"
output: 
    distill::distill_article:
        highlight: kate
        code_folding: false  
        toc: true            
        toc_depth: 2         
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE,
                      fig.width = 10, fig.height = 13, 
                      dev = "ragg_png", res = 1000, retina = 1)
```

# Setup

```{r prep}
pacman::p_load("tidyverse", "here", "glue", "labelled", "sf", "geojsonsf", "patchwork", "pdftools")
```


# Grid-Daten

## CSV

```{r grid-constituencies-csv}
## csv mit nur Wahlkreisen, für Tile Map
#write_csv(dat_erst_winneronly_dw %>% dplyr::select(Wahlkreisname), here("data", "wk.csv"))

## Grid Preparation für Labels und Bundesländer
grid <-
  read_csv(here("data", "wk_grid_raw.csv")) %>%
  mutate(
    id = str_sub(Wahlkreisname, 1, 3),
    id_num = as.numeric(id),
    wk = str_sub(Wahlkreisname, 5, nchar(Wahlkreisname)),
    bundesland_de = case_when(
      id_num %in% 1:11 ~ "Schleswig-Holstein",
      id_num %in% 12:17 ~ "Mecklenburg-Vorpommern",
      id_num %in% 18:23 ~ "Hamburg",
      id_num %in% 24:53 ~ "Niedersachsen",
      id_num %in% 54:55 ~ "Bremen",
      id_num %in% 56:65 ~ "Brandenburg",
      id_num %in% 66:74 ~ "Sachsen-Anhalt",
      id_num %in% 75:86 ~ "Berlin",
      id_num %in% 87:150 ~ "Nordrhein-Westfalen",
      id_num %in% 151:166 ~ "Sachsen",
      id_num %in% 167:188 ~ "Hessen",
      id_num %in% 189:196 ~ "Thüringen",
      id_num %in% 197:211 ~ "Rheinland-Pfalz",
      id_num %in% 212:257 ~ "Bayern",
      id_num %in% 258:295 ~ "Baden-Württemberg",
      id_num %in% 296:299 ~ "Saarland"
    ),
    bundesland_en = case_when(
      id_num %in% 1:11 ~ "Schleswig-Holstein",
      id_num %in% 12:17 ~ "Mecklenburg-Western Pomerania",
      id_num %in% 18:23 ~ "Hamburg",
      id_num %in% 24:53 ~ "Lower Saxony",
      id_num %in% 54:55 ~ "Bremen",
      id_num %in% 56:65 ~ "Brandenburg",
      id_num %in% 66:74 ~ "Saxony-Anhalt",
      id_num %in% 75:86 ~ "Berlin",
      id_num %in% 87:150 ~ "North Rhine-Westphalia",
      id_num %in% 151:166 ~ "Saxony",
      id_num %in% 167:188 ~ "Hesse",
      id_num %in% 189:196 ~ "Thuringia",
      id_num %in% 197:211 ~ "Rheinland-Pfalz",
      id_num %in% 212:257 ~ "Bavaria",
      id_num %in% 258:295 ~ "Baden-Württemberg",
      id_num %in% 296:299 ~ "Saarland"
    )
  ) %>% 
  arrange(id_num) %>% 
  dplyr::select(
    wk_full = Wahlkreisname,
    wk, id, bundesland_de, bundesland_en,
    col, row
  )

write_csv(grid, here("data", "de_constituencies_grid.csv"))

grid <- read_csv(here("data", "de_constituencies_grid.csv"))
```

## GEOJSON

```{r grid-as-geojson}
# Koordinaten auf ungefähre Koordinaten Deutschlands normalisieren
bb_germany <- osmdata::getbb("Germany", featuretype = "country")

grid_normalized <- 
  grid %>% 
  select(wk, row, col) %>% 
  mutate(row = max(row) - row + 1,
         lat = row/max(row) * (bb_germany["y", "max"] - bb_germany["y", "min"]) + 
           bb_germany["y", "min"],
         lon = col/max(col) * (bb_germany["x", "max"] - bb_germany["x", "min"]) + 
           bb_germany["x", "min"])

bb_germany
summary(grid_normalized$lat)
summary(grid_normalized$lon)


# # Grid-Koordinaten in sf-Geometry übersetzen
# grid_sf_points <- grid %>% 
#   # Zeilennummern (row) drehen
#   mutate(row = max(row) - row + 1) %>% 
#   st_as_sf(coords = c("col", "row"))
# str(grid_sf_points)


# Grid-Koordinaten in sf-Geometry übersetzen
grid_sf_points <- grid_normalized %>% 
  st_as_sf(coords = c("lon", "lat"))
str(grid_sf_points)

ggplot(grid_sf_points) +
  geom_sf() +
  coord_sf()


#' Convert sf objects to GeoJSON format
#' https://cran.r-project.org/web/packages/geojsonsf/vignettes/geojson-sf-conversions.html#what-it-does
grid_geojson_pts <- sf_geojson(grid_sf_points)
write_file(grid_geojson_pts, here("data", "de_constituencies_points.geojson.json"))
```


# Tile Grid Maps

```{r, colors}
set.seed(1234567890)
pal <- sample(ggsci::pal_simpsons()(16))
```

## Bundesländer

```{r map-bundesländer, fig.wdith=10, fig.height=10}
theme_set(theme_void(base_size = 16, base_family = "Editorial New")) #Editorial New, Noto Serif
theme_update(legend.margin = margin(0, 0, 0, 25),
             legend.text = element_text(margin = margin(5, 0, 5, 0)),
             plot.title = element_text(hjust = .5, face = "bold", 
                                       lineheight = 1.1, margin = margin(t = 10, b = 20)),
             plot.subtitle = element_text(hjust = .5, color = "grey40", size = 15,
                                          margin = margin(t = -8, b = 18)),
             plot.title.position = "plot",
             plot.caption = element_text(hjust = 0, color = "grey40", 
                                         lineheight = 1.3,
                                         size = 9, margin = margin(20, 0, 5, 0)),
             plot.caption.position = "plot",
             plot.margin = margin(10, 0, 10, 0))

## Deutsche Version
ggplot(grid, aes(col, row, color = bundesland_de, fill = bundesland_de)) +
  geom_tile(size = 3, color = "#212121") +
  geom_tile(size = .01) +
  coord_fixed() +
  scale_x_continuous(expand = c(.01, .01), limits = c(-.5, max(grid$col) + .5)) +
  scale_y_reverse(expand = c(.03, .03)) +
  scale_color_manual(values = pal, name = NULL) +
  scale_fill_manual(values = pal, name = NULL) + 
  theme(plot.margin = margin(15, 10, 15, 0)) +
  labs(title = "Tile Grid Karte der Wahlkreise Deutschlands", caption = "Design: Cédric Scherer & Ansgar Wolsing")

ggsave(here("plots", "grid_laender_de.pdf"), width = 10, height = 10, device = cairo_pdf)

## Englische Version
ggplot(grid, aes(col, row, color = bundesland_en, fill = bundesland_en)) +
  geom_tile(size = 3, color = "#212121") +
  geom_tile(size = .01) +
  coord_fixed() +
  scale_x_continuous(expand = c(.01, .01), limits = c(-.5, max(grid$col) + .5)) +
  scale_y_reverse(expand = c(.03, .03)) +
  scale_color_manual(values = pal, name = NULL) +
  scale_fill_manual(values = pal, name = NULL) + 
  theme(plot.margin = margin(15, 10, 15, 0)) + 
  labs(title = "Tile Grid Map of Germany's Constituencies", caption = "Design: Cédric Scherer & Ansgar Wolsing")

ggsave(here("plots", "grid_laender_en.pdf"), width = 10, height = 10, device = cairo_pdf)
```


## Varianten Tile Grid Map

```{r map-bundesländer-varianten, fig.wdith=25, fig.height=15.5}
theme_set(theme_void(base_size = 24, base_family = "Editorial New")) #Editorial New, Noto Serif
theme_update(legend.margin = margin(0, 0, 50, 0),
             legend.text = element_text(margin = margin(5, 15, 5, 0)),
             legend.position = "top",
             plot.title = element_text(hjust = .5, face = "bold", size = 40,
                                       lineheight = 1.1, margin = margin(t = 10, b = 25)),
             plot.subtitle = element_text(hjust = .5, color = "grey40", size = 15,
                                          margin = margin(t = -8, b = 18)),
             plot.title.position = "plot",
             plot.caption = element_text(hjust = .5, color = "grey30", 
                                         lineheight = 1.3,
                                         size = 18, margin = margin(20, 0, 5, 0)),
             plot.caption.position = "plot",
             plot.margin = margin(10, 0, 10, 0))

## Deutsche Version
ggplot(grid, aes(col, row, color = bundesland_de, fill = bundesland_de)) +
  geom_tile(size = 3, color = "#212121") +
  geom_tile(size = .01) +
  coord_fixed() +
  scale_x_continuous(expand = c(.01, .01), limits = c(-.5, max(grid$col) + .5)) +
  scale_y_reverse(expand = c(.03, .03)) +
  scale_color_manual(values = pal, guide = "none") +
  scale_fill_manual(values = pal, guide = "none") + 
  theme(plot.margin = margin(15, 10, 15, 0)) -> g1

ggplot(grid, aes(col, row, color = bundesland_de, color = bundesland_de)) +
  geom_point(size = 11, shape = 15) +
  coord_fixed() +
  scale_x_continuous(expand = c(.01, .01), limits = c(-.5, max(grid$col) + .5)) +
  scale_y_reverse(expand = c(.03, .03)) +
  scale_color_manual(values = pal, name = NULL) +
  guides(color = guide_legend(nrow = 2)) +
  theme(plot.margin = margin(15, 10, 15, 0)) -> g2

ggplot(grid, aes(col, row, color = bundesland_de, color = bundesland_de)) +
  geom_point(
    aes(fill = bundesland_de), 
    size = 9, shape = 21, stroke = 2, alpha = .5, color = "transparent"
  ) +
  geom_point(
    aes(color = bundesland_de), 
    size = 9, shape = 21, stroke = 2, fill = "transparent"
  ) +
  coord_fixed() +
  scale_x_continuous(expand = c(.01, .01), limits = c(-.5, max(grid$col) + .5)) +
  scale_y_reverse(expand = c(.03, .03)) +
  scale_color_manual(values = pal, guide = "none") +
  scale_fill_manual(values = pal, guide = "none") +
  theme(plot.margin = margin(15, 10, 15, 0)) -> g3

g1 + g2 + g3 + plot_layout(nrow = 1, guides = "collect") + plot_annotation(title = "Kachelkarte der 299 Wahlkreise Deutschlands", caption = "Design: Cédric Scherer & Ansgar Wolsing")

ggsave(here("plots", "grid_laender_variants_de.pdf"), width = 25, height = 15.5, device = cairo_pdf)

## Englische Version
ggplot(grid, aes(col, row, color = bundesland_en, color = bundesland_en)) +
  geom_point(size = 11, shape = 15) +
  coord_fixed() +
  scale_x_continuous(expand = c(.01, .01), limits = c(-.5, max(grid$col) + .5)) +
  scale_y_reverse(expand = c(.03, .03)) +
  scale_color_manual(values = pal, name = NULL) +
  guides(color = guide_legend(nrow = 2)) +
  theme(plot.margin = margin(15, 10, 15, 0)) -> g2

g1 + g2 + g3 + plot_layout(nrow = 1, guides = "collect") + plot_annotation(title = "Tile Grid Map of the 299 Constituencies of Germany", caption = "Design: Cédric Scherer & Ansgar Wolsing")

ggsave(here("plots", "grid_laender_variants_en.pdf"), width = 25, height = 15.5, device = cairo_pdf)
```

```{r convert}
pdfs <- list.files(here(), pattern = "*.pdf", recursive = TRUE)
for(pdf in pdfs) {
  pdf_convert(pdf = glue("{here()}/{pdf}"), 
              filenames = glue("{here()}/{str_remove(pdf, '.pdf')}.png"),
              format = "png", dpi = 500)
}
```


***

<details><summary>Session Info</summary>

```{r sessionInfo}
Sys.time()
sessionInfo()
```

</details>
